<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="terms-conditions.aspx.cs" Inherits="Avowapparel.terms_conditions" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 id="page-title" class="title">Terms &amp; Conditions</h1>
<div id="block-system-main" class="block block-system block-even">
<div>
<div class="ds-1col node node-page view-mode-full  clearfix">
 
<div class="field field-name-body field-type-text-with-summary field-label-hidden">
<div class="field-items">
<div class="field-item even"><p>Thank you for visiting AvowApparel.com. By visiting this site or purchasing merchandise from this site you agree to be legally bound by and comply with the terms and conditions outlined in this policy. By agreeing to the terms and conditions of use of this site you agree to all of the policies and procedures associated with the site. The owners of this site reserve the right to update this, and all other policies associated with this site at any time without notice. Please be sure to check all of the policies on this site for updates. Your use of this site constitutes your agreement to follow and be bound by the terms as changed/updated. (Note: For this, and all Policies on this site, ‘Avow Apparel’ refers to the parent company Avow LLC.)</p>
<p><strong>Proprietary Rights</strong></p>
<p>All content including but not limited to imagery, text, video, audio, photographs, illustrations, designs, graphics, logos, and trademarks are owned by Avow Apparel. All trademarks are protected by the United States Patent and Trademark Office. The content on this site is intended solely for personal non-commercial use by users of this site. Content on this site may not be reproduced, sold, distributed, publicly displayed, published, modified, or edited in any way. Use of content on this site for purposes other than the one stated in this policy are strictly prohibited.</p>
<p><strong>Avow Apparel Trademarks</strong></p>
<p>All names, logos, designs, and other designations that are displayed or used in connection with this site are owned by Avow Apparel. You may not use Avow Apparel trademarks without prior written authorization of Avow Apparel except to identify the products or services of the company and only if your reference is truthful and not misleading. The products, logos, designs, photographs, advertisements and images displayed on this site may be the subject of other intellectual property rights reserved by Avow Apparel, or other third parties.</p>
<p><strong>Third Party Sites</strong></p>
<p>This site may provide links to third party sites. These links are for your convenience only. Avow Apparel does not guarantee the availability, accuracy, or reliability of any policy, information, or content in third party sites. Avow Apparel, is not responsible for any damages, injury, or any other inconveniences that may occur from the use of third party sites. Access and use of content in third party sites is solely at your own risk. Links to third party sites do not constitute endorsement of the sites or of their content by Avow Apparel.</p>
<p><strong>User Participation</strong></p>
<p>Any Material submitted by a user (you) to Avow Apparel, (AvowApparel.com) via electronic mail or by any other method (this Material includes but is not limited to comments, feedback, photographs, creative ideas, suggestions, designs, and artwork.) will be deemed non-confidential. By posting or submitting the Material outlined in this policy you grant Avow Apparel, the right to use such Material in any media, by any means, and for any purpose. Under no circumstance is Avow Apparel, obligated to pay or give any type of compensation for use of such material. All such Material, once submitted through the means stated in this policy, will become and remain the property of Avow Apparel. You (the user) agree that you are solely responsible for all Material submitted by you. You represent that you own all of the rights to Material submitted by you and that use of such Material by Avow Apparel, will not infringe or violate any rights of any third party. You agree to defend, indemnify, and hold Avow Apparel, and its affiliates (including but not limited to its employees, representatives, sponsors, partners, suppliers, collectively its “Affiliates”) harmless from and against any and all claims, liabilities, damages, costs, and expenses (including all legal costs and attorneys’ fees) arising from or in connection with any and all Material submitted by you. Avow Apparel, at its sole discretion, reserves the right to remove, edit, or move any Material posted or submitted by you. By participating in surveys, contests, mailing lists, or any other promotions on AvowApparel.com you hereby agree that Avow Apparel, may use information about you for product development, marketing, and promotional purposes. You agree that Avow Apparel, may use information about you and your use of this site in any manner, which does not reveal your identity and is in accordance with the terms of the Avow Apparel Privacy Policy. You also agree that Avow Apparel, may send you electronic mail in order to provide you with updates to the site, information regarding products, or for other such purposes that Avow Apparel, deems appropriate. </p>
<p><strong>Avow Apparel Products</strong></p>
<p>The Avow Apparel products displayed on AvowApparel.com may be available on this site and at other select retail locations and/or events. Avow Apparel, cannot and does not guarantee that the products appearing on this site will be available at any given time. Availability of products displayed on this site are subject to supply. Avow Apparel, reserves the right to change product descriptions, specifications, colors, and prices at any time without notice. All prices displayed on this site are quoted in United States dollars and are valid and effective only in the United States. The technical specifications and settings on your computer and its display may affect the accuracy of the colors offered on this site. </p>
<p><strong>Disclaimer of Warranties</strong></p>
<p>This site, AvowApparel.com, and its content are provided ‘as is’ for your use. To the extent permitted by law, this site and its content are provided without warranties of any kind, either expressed or implied, including but without limitation to warranties of title, merchantability, fitness for a particular purpose, and non-infringement. Avow Apparel, does not warrant or guarantee that all content is accurate, reliable, or correct. Avow Apparel, does not warrant or guarantee that this site will be available at any particular time or location, that any defects or errors will be corrected, or that all content is free of viruses or other harmful components. You assume full responsibility for all costs associated withal necessary servicing or<br>
repairs of any equipment you use in connection with AvowApparel.com. Avow Apparel, is not liable for any damages of any kind related to your use of this site. Your use of this site and its content is entirely at your own risk.</p>
<p><strong>Limitation of Liability</strong></p>
<p>In no event shall Avow Apparel, or its affiliates, be liable under contract or otherwise for any indirect, incidental, exemplary, special, punitive, or consequential damages arising from or in connection with the use, inability to use, performance of the information, services, products, and materials available from this site regardless of whether or not AvowApparel.com or any of its Affiliates have been advised of the<br>
possibility of such loss or damages, except where prohibited by law.</p>
<p><strong>Indemnification of AvowApparel.com</strong></p>
<p>You agree to defend, indemnify, and hold Avow Apparel, and its affiliates harmless from and against any and all claims, losses, damages, liabilities, costs, and expenses (including but without limitation to legal costs and attorneys’ fees) arising from or in connection with your use or misuse of this site and the content or your violation of any provision of this Policy.</p>
<p><strong>International Use</strong></p>
<p>Avow Apparel, makes no representation or warranty that this site and its contents are appropriate for use outside of the United States. Accessing this site or its content from territories in which the site or content is illegal is strictly prohibited. You agree that if you choose to access this site or its content from any other locations outside of the United States you do so on your own initiative and are solely responsible for compliance with local laws. </p>
<p><strong>Information</strong></p>
<p>If there is a dispute in regards to this Policy or your use of this site, the laws of the State of California, United States of America, shall apply, without regard to any conflict of law provisions, and it shall be resolved exclusively by the state and federal courts sitting in Alameda County, in the State of California, United States of America.</p>
<p>For questions about this policy please contact <a href="mailto:Info@AvowApparel.com">Info@AvowApparel.com<script cf-hash="f9e31" type="text/javascript">
/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.currentScript:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=parseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=String.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c)}}}catch(u){}}();/* ]]> */</script></a>.</p>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="block-mailchimp-lists-website-signup" class="block block-mailchimp-lists block-odd">
<h2 class="block-title">Join Our Mailing List</h2>
<div>
<form class="mailchimp-lists-user-subscribe-form" action="/terms-conditions" method="post" id="mailchimp-lists-user-subscribe-form-website-signup" accept-charset="UTF-8"><div><div id="mailchimp-newsletter-website_signup" class="mailchimp-newsletter-wrapper"><div id="edit-mailchimp-lists-mailchimp-website-signup-title" class="form-item form-type-item">
</div>
<div class="form-item form-type-textfield form-item-mailchimp-lists-mailchimp-website-signup-mergevars-EMAIL">
<label for="edit-mailchimp-lists-mailchimp-website-signup-mergevars-email"><span class="secondary label">Email Address</span> <span class="form-required" title="This field is required.">*</span></label>
<input placeholder="email" type="text" id="edit-mailchimp-lists-mailchimp-website-signup-mergevars-email" name="mailchimp_lists[mailchimp_website_signup][mergevars][EMAIL]" value="" size="25" maxlength="128" class="form-text required">
</div>
<p class="notice-join">Join our mailing list for information on events, new collections, special offers, and all things Avow!</p></div><input type="submit" id="edit-submit" name="op" value="Join" class="form-submit"><input type="hidden" name="form_build_id" value="form-g70kzPCOn9R4tM1iha1s1FYiFihKYi2nZcMWlL0iDpU">
<input type="hidden" name="form_id" value="mailchimp_lists_user_subscribe_form_website_signup">
</div></form> </div>
</div>
</asp:Content>
